### ISSUE TITLE
Altitude erronée

### ISSUE THREAD

**Issue by ChristopheMonget** [jhemmi/QgisPhysiocapPlugin#27]
Bonjour, 

L'enregistrement des données en zone d'altitude négative n'est pas fonctionnelle. 

Dans les fichiers brutes nous avons "0.-8" au lieu de "-0.8".

Y-a-t-il possibilité d'effacer les altitudes posant problème pour supprimer les erreurs sur le pluging?

Bonne journée

**Comment by jhemmi** [comment]
Ereca a solutionné en corrigeant l’erreur d’écriture

Contournement, retrouver la ligne en erreur à l'aide des traces de l'extension Physiocap. Editer votre fichier MID et supprimer les lignes en erreur.
