### ISSUE TITLE
Version de QGIS ou installation de QGIS ? (à rapprocher de l'issue 29)

### ISSUE THREAD

**Issue by ChristopheMonget** [jhemmi/QgisPhysiocapPlugin#31]
Bonjour, 
![issue pluging physiocap](https://cloud.githubusercontent.com/assets/16386848/14276508/73834b98-fb1f-11e5-9243-23e95bff428d.PNG)

J'ai mis à jour le pluging physicap ce matin. La visualisation des histogrammes n'est pas possible. 

Quelle version de qgis doit-être installé?

**Comment by jhemmi** [comment]
Il s'agit d'un **problème d'installation QGIS** et non de sa version.
L'extension tourne avec les versions QGIS 2.4 à 2.14.0 (tester sous Windows 64). Mais certaines installation (en Win32, avec l'installateur OSGEO...) provoquant un blocage lors du calcul d'histogramme (cf issue 29). J'ai  verrouillé au démarrage de l'extension par un test sur l'accès au module imaging qui sera nécessaire aux histogrammes.

_Dans cette installation, les histogrammes ne fonctionneront pas._
Le fait que le message apparaisse suite à l'installation du plugin est lié au fait que ce message est apparu avec la version 1.3.2. Mais sur cette machine, il est très probable que les histogrammes, si ils était demandés, provoquaient un blocage du plugin ( cf issu 29).

Le ticket soumis à l'Osgeo a été rafraîchi (ce matin toujours cf issue 29) car il n'est pas pris en compte et ne le sera peut être pas vu le peu de machines 32 bits...

Merci de documenter quelle est le contexte de l'installation : 
Windows 32 bits ou 64 ? (cf panneau de configuratioin => System => Type du systeme)
Version QGIS ? 
installateur indépendant ou OSGEO  (64 ou 32 bits) cf http://qgis.org/fr/site/forusers/download.html

**Mon conseil est d'installer avec l'installateur indépendant** qui n'a pas (à ma connaissance) encore vécu ce problème.

`Autre** possibilité de contournement**, depuis 2.12 QGIS propose des histogrammes dans les propriétés de la couche qui peuvent remplacer le fonctionnel histo du plugin.`

Merci pour ta contribution.

**Comment by jhemmi** [comment]
Fermer par erreur
