### ISSUE TITLE
QGIS 2.14.8 - Génération Carte Inter et Intra parcellaire KO

### ISSUE THREAD

**Issue by ThomasSiret** [jhemmi/QgisPhysiocapPlugin#36]
Bonjour,

J'utilise QGIS 2.14.8 pour le plugin Physiocap mais depuis plusieurs jours je n'arrive plus à générer les cartes de moyenne parcellaire inter et intra.
Lors du démarrage de QGIS (dans la boite de dialogue) je retrouve ces messages d'erreur:

![capture2](https://cloud.githubusercontent.com/assets/23697548/20591518/37817b94-b229-11e6-9198-b9c7e37e5fab.PNG)
![capture3](https://cloud.githubusercontent.com/assets/23697548/20591536/4daa81ae-b229-11e6-9aba-946819ffb403.PNG)

Puis après le lancement des "Moyennes Inter Parcellaire", ce message apparaît

![capture](https://cloud.githubusercontent.com/assets/23697548/20591335/53ffcb14-b228-11e6-85b0-36a4111f6cdd.PNG)

Si je force jusqu'à l'interpolation des données (en rafraîchissant les listes de vecteurs), j'obtiens d'autres messages d'erreurs 

![capture4](https://cloud.githubusercontent.com/assets/23697548/20591683/3a08dc6c-b22a-11e6-953c-bd000cac08a7.PNG)
![capture5](https://cloud.githubusercontent.com/assets/23697548/20591749/876d4e66-b22a-11e6-8870-580d807e97ef.PNG)
![capture6](https://cloud.githubusercontent.com/assets/23697548/20591753/89e50a94-b22a-11e6-8fc8-692c54f41e34.PNG)

**Comment by jhemmi** [comment]
Bonjour,
Merci pour votre retour.
Pouvez-vous me faire passer un jeu de donnees ? Je n'ai pas testé au dela
de 2.14.1
Merci aussi de me faire une copie d'ecran de aide => a propos

Etes vous sur une installation en 64bits et quelle version fonctionnait
avant 2.14.8

Bonne journée
Jean

**Comment by ThomasSiret** [comment]
Je suis bien installé en 64 bit et ce que je ne m'explique pas, c'est que tout fonctionnait très bien sur la version 2.14.8 et que d'un coup plus rien ne fonctionnait pour les cartes inter et intra.

Auparavant il n'y avait pas QGIS sur cette ordinateur.

Voici la capture de mon à propos
![capture7](https://cloud.githubusercontent.com/assets/23697548/20597852/5bc707a4-b246-11e6-881d-5d74ade75a3a.PNG)

Ci-joint un jeu de donnée test

Merci de votre aide et de votre réactivité !
Thomas

**Comment by jhemmi** [comment]
Il me faut vous demander le shapefile de contour avec lequel les calculs
parcellaires tombent en erreur.

En effet, votre jeu de données tourne sous 2.8. sous linux
mais aussi sous 2.14.8 LTR sous windows
Le problème est donc lié 
- à votre contour (vérifier la validité de votre contour dans QGIS et extension Ftools, menu Vecteur = > Outils de géométrie => Vérifier la validité de votre géométrie)
- à une installation problématique dans processing (traitement)

**Comment by jhemmi** [comment]
Bonjour,
Le problème n'est pas reproduit sur mon installation 2.14.8 LTR.
Il s'agit probablement d'un contour non valide.

Meilleures salutations
![donnees-siret-sousqgis2 14 8](https://cloud.githubusercontent.com/assets/13019152/20616085/ce273f0a-b2df-11e6-913d-9ae93933e9f5.png)

​Jean​

**Comment by ThomasSiret** [comment]
Bonjour, 

En effet, c'était bien le fichier contour parcellaire qui était non valide.

Merci beaucoup de votre aide !
Thomas
