### ISSUE TITLE
Problème Interpo

### ISSUE THREAD

**Issue by ThomasSiret** [jhemmi/QgisPhysiocapPlugin#37]
Bonjour Jean,

QGIS me génère un message d'erreur lors de l'interpolation pour BIOM, DIAM, NBSARM.

![generation interpo qgis pc](https://cloud.githubusercontent.com/assets/23697548/21977542/dafea810-dbd6-11e6-97f0-48997305f384.PNG)

Serait-ce dû à des fichiers corrompus ?? QGIS ? Ce que je m'explique pas c'est que cela n'est pas systématique. 

Bonne journée
Thomas

**Comment by jhemmi** [comment]
Bonjour,
Il s'agit certainement du mot "après midi". L'interface plugin-processing-SAGA bloque avec un caractère non ascii "è" (cf issu 28 que je n'arrive pas à faire résoudre).
Le contournement est d'utiliser PM ou AM dans votre nommage.
Cdt
